### ISSUE TITLE
.gitmodules should specify the OZ version as v4.

### ISSUE THREAD

**Issue by imp0wd3r** [nayms/contracts-v3#83]
The OZ master branch is currently at version 5.0.0, which requires Solidity version ^0.8.20. This conflicts with the project's current version of 0.8.17.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/ECDSA.sol

Therefore, the following error will be reported during the build:
```
Found incompatible Solidity versions:
    src/diamonds/nayms/AppStorage.sol (0.8.17)
    lib/ozv4/contracts/utils/cryptography/ECDSA.sol (^0.8.20)
```

This can be fixed by specifying the branch in the .gitmodules file:
```
[submodule "lib/ozv4"]
	path = lib/ozv4
	url = https://github.com/openzeppelin/openzeppelin-contracts
	branch = release-v4.8
```

**Comment by kevin-fruitful** [comment]
Hi imp0wd3r,

Thanks for opening an issue. I just bumped our contracts to use 0.8.20 and refactored the code to use openzeppelin branch merge/release-v5.0. Let me know if you spot anymore issues, thanks!

**Comment by imp0wd3r** [comment]
Thank you for your prompt response. 

I heard that OZ 4.x to 5.x have made many updates. I haven't looked into the details, but I hope you can understand them before upgrading to avoid compatibility issues.

Additionally, I've submitted a new report on Immunefi, number 24944, I discovered this issue while writing the report. I hope you can review it to determine its validity.

**Comment by kevin-fruitful** [comment]
I'm reviewing 24944 and get back to you ASAP! Really appreciate it :)
